VCMI_PATH_PREBUILT := $(PROJECT_PATH_BASE)/prebuilt-include
VCMI_PATH_EXT := $(PROJECT_PATH_BASE)/ext
VCMI_PATH_MAIN := $(PROJECT_PATH_BASE)/project

VCMI_PATH_SDL := $(VCMI_PATH_EXT)/SDL2
VCMI_PATH_FFMPEG := $(PROJECT_PATH_BASE)/ff/ffmpeg
VCMI_PATH_BOOST := $(VCMI_PATH_EXT)/boost/boost_1_61_0
VCMI_PATH_VCMI := $(VCMI_PATH_MAIN)/jni/vcmi-app/vcmi-app

VCMI_INCL_VCMI := $(VCMI_PATH_VCMI) $(VCMI_PATH_VCMI)/include
VCMI_INCL_BOOST := $(VCMI_PATH_BOOST)
VCMI_INCL_FFMPEG := $(VCMI_PATH_FFMPEG)/android/armeabi/include
VCMI_INCL_SDL := $(VCMI_PATH_SDL)/core/code/include